networks:
  minecraft-network:
    driver: bridge    
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:
  lazymc:
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    networks:
      minecraft-network:
        ipv4_address: 172.19.0.2
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/appdata/mc/data:/server:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "25565:25565"
  mc:
    image: itzg/minecraft-server
    networks:
      minecraft-network:
        ipv4_address: 172.19.0.3
    tty: true
    stdin_open: true
    labels:
      - lazymc.enabled=true
      - lazymc.group=mc
      - lazymc.server.address=mc:25565
    environment:
      EULA: "TRUE"
      TZ: $TZ
      VERSION: "1.21.4"
      ICON: "/data/ai_flying_cow.jpeg"
      OVERRIDE_ICON: "TRUE"
      SEED: "flyingkows"
      SERVER_NAME: "Flying Kows"
      MOTD: "Harry's Minecraft Server"
      DIFFICULTY: "normal"
      RESOURCE_PACK: "https://drive.usercontent.google.com/uc?id=1pX7h1xwOcV30mADx6YWY_5elLJVU_cJP&export=download"
      RESOURCE_PACK_SHA1: "1befd1dc9e0d5158bbbe2a4b29f6ebad1fe7af81"
      RESOURCE_PACK_ENFORCE: "TRUE"
      MEMORY: "8G"
      VIEW_DISTANCE: 12
    restart: no
    volumes:
      - $DOCKERDIR/appdata/mc/data:/data
  mc-backup:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      PRUNE_BACKUP_DAYS: 3
      RCON_HOST: mc
      INITIAL_DELAY: "2m"
      PAUSE_IF_NO_PLAYERS: true
      TZ: $TZ
    volumes:
      - $DOCKERDIR/appdata/mc/data:/data:ro
      - $DOCKERDIR/appdata/mc/backups:/backups